const fs = require('fs');
const csv = require('csv-parser');
const createCsvWriter = require('csv-writer').createObjectCsvWriter;

const results = [];
fs.createReadStream('flow_cleaned_4col.csv')
  .pipe(csv())
  .on('data', (data) => results.push(data))
  .on('end', () => {
    let currentFileName = '';
    for (const r of results) {
        if (r['File Name'] && r['File Name'].trim() !== '') {
            currentFileName = r['File Name'];
        } else {
            r['File Name'] = currentFileName;
        }
    }

    const recordsWithout2_4 = results.filter(r => !r['File Name'].includes('2.4 Project Kickoff'));

    const new2_4 = [
      ['2.4 Project Kickoff - SCDF', '2.4.1', '[N/A]', 'STAGE 2.4.1: CONNECT STAKEHOLDERS', '2.4.1.1'],
      ['2.4 Project Kickoff - SCDF', '2.4.1.1', 'Sales Executive', 'Sends list of required docs in Client Group Chat (Requested Information: Layout plan OR photos of the premises, ACRA, NRIC of Director, Contact Number, Email. To-Be: Decision > is it an existing unit or bare unit? Development of checklist for site visit, Collation of evidence required).', '2.4.1.2'],
      ['2.4 Project Kickoff - SCDF', '2.4.1.2', 'Client', 'Has Client given the necessary documents?', '2.4.1.3, 2.4.1.4'],
      ['2.4 Project Kickoff - SCDF', '2.4.1.3', 'Client', 'If yes, Sends requested Docs & Information.', '2.4.2, 2.4.3'],
      ['2.4 Project Kickoff - SCDF', '2.4.1.4', 'Sales Executive', 'If no, Follow up with Client on list of documents.', '2.4.1.2'],

      ['2.4 Project Kickoff - SCDF', '2.4.2', '[N/A]', 'STAGE 2.4.2: PREPARE LETTER OF AUTHORISATION', '2.4.2.1'],
      ['2.4 Project Kickoff - SCDF', '2.4.2.1', 'Sales Executive', 'Review received documents & information.', '2.4.2.2'],
      ['2.4 Project Kickoff - SCDF', '2.4.2.2', 'Sales Executive', 'Prepare Letter of Authorisation (LoA).', '2.4.2.3'],
      ['2.4 Project Kickoff - SCDF', '2.4.2.3', 'Sales Executive', 'Send LoA to client for execution.', '2.4.2.4'],
      ['2.4 Project Kickoff - SCDF', '2.4.2.4', 'Client', 'Executes LoA.', '2.4.2.5'],
      ['2.4 Project Kickoff - SCDF', '2.4.2.5', 'Client', 'Sends executed LoA to Admin.', '2.4.2.6'],
      ['2.4 Project Kickoff - SCDF', '2.4.2.6', 'Admin', 'Receives LoA.', '2.4.4'],

      ['2.4 Project Kickoff - SCDF', '2.4.3', '[N/A]', 'STAGE 2.4.3: REGISTER PROJECT ON CORENET & OBTAIN FORMS FOR PROJECT', '2.4.3.1'],
      ['2.4 Project Kickoff - SCDF', '2.4.3.1', 'Admin', 'Register project on Corenet.', '2.4.3.2'],
      ['2.4 Project Kickoff - SCDF', '2.4.3.2', 'Admin', 'Obtain project reference number.', '2.4.3.3'],
      ['2.4 Project Kickoff - SCDF', '2.4.3.3', 'Admin', "Download Forms (Depending on department submitting to, different forms will be auto-generated by the Corenet's system).", '2.4.3.4'],
      ['2.4 Project Kickoff - SCDF', '2.4.3.4', 'Admin', 'Fill up Forms.', '2.4.3.5'],
      ['2.4 Project Kickoff - SCDF', '2.4.3.5', 'Admin', 'Save draft Forms in working folder for subsequent submission.', '2.4.4'],

      ['2.4 Project Kickoff - SCDF', '2.4.4', '[N/A]', 'STAGE 2.4.4: PREPARE DETAILED DRAWINGS FOR REGULATORY COMPLIANCE', '2.4.4.1'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.1', 'Project Manager', 'Prepare Building Plan (BP) (Necessary documents required to prepare first draft of BP by PM include: BP (Whole Storey Plan), Proposed layout plan (by client); and/or site photos/videos).', '2.4.4.2'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.2', 'Admin', 'Send necessary documents to Freelancer to draw MV (Documents to be sent to Freelancer: 1. Building Plan (Draft BP), as prepared by PM. 2. Proposed layout plan (by client); and 3. Site photos/videos).', '2.4.4.3'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.3', 'Freelancers', 'Prepare detailed drawings (Documents required to be prepared by Freelancer: 1. Detailed drawings: a. Building Plan (Revised BP), as prepared by Freelancer, b. Mechanical Ventilation (MV), c. Fire suppression / Sprinklers (FP)).', '2.4.4.4'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.4', 'Freelancers', 'Send detailed drawings to PM & SE.', '2.4.4.5, 2.4.4.6'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.5', 'Sales Executive', 'Receive detailed drawings by Freelancer.', '2.4.4.7'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.6', 'Project Manager', 'Receive detailed drawings by Freelancer.', '2.4.4.8'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.7', 'Sales Executive', 'SE checks for whether revisions tally with site condition.', '2.4.4.9'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.8', 'Project Manager', 'PM checks for regulatory compliance (FS code, etc).', '2.4.4.9'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.9', 'Sales Executive', 'Are there revisions to be made by Freelancer? (Joint review by PM and SE)', '2.4.4.10, 2.4.4.12'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.10', 'Sales Executive', 'If yes, Instructs Freelancers on revisions.', '2.4.4.11'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.11', 'Sales Executive', 'Revise detailed drawings by Freelancer.', '2.4.4.3'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.12', 'Project Manager', 'If no, Collate and send detailed drawings (BP, MV) to Vetter/RI for approval.', '2.4.4.13'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.13', 'Vetter / Registered Inspector', 'Receive detailed drawings.', '2.4.4.14'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.14', 'Vetter / Registered Inspector', 'Are the detailed drawings approved by Vetter/RI?', '2.4.5, 2.4.4.15'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.15', 'Project Manager', "If no, Collate Vetter/RI's comments & revisions.", '2.4.4.16'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.16', 'Project Manager', 'Revise Building Plan (BP).', '2.4.4.17'],
      ['2.4 Project Kickoff - SCDF', '2.4.4.17', 'Project Manager', 'Instructs Freelancers on revisions.', '2.4.4.3'],

      ['2.4 Project Kickoff - SCDF', '2.4.5', '[N/A]', 'STAGE 2.4.5: ENDORSE & ENCRYPT DETAILED DRAWINGS', '2.4.5.1'],
      ['2.4 Project Kickoff - SCDF', '2.4.5.1', 'Project Manager', 'Send detailed drawings to Qualified Persons (QP).', '2.4.5.2, 2.4.5.6'],
      ['2.4 Project Kickoff - SCDF', '2.4.5.2', 'Mechanical Engineer', 'Receives MV.', '2.4.5.3'],
      ['2.4 Project Kickoff - SCDF', '2.4.5.3', 'Mechanical Engineer', 'Endorses & encrypts MV.', '2.4.5.4'],
      ['2.4 Project Kickoff - SCDF', '2.4.5.4', 'Mechanical Engineer', 'Sends to PM.', '2.4.5.5'],
      ['2.4 Project Kickoff - SCDF', '2.4.5.5', 'Project Manager', 'Receives endorsed & encrypted ACMV.', '2.4.5.11'],
      ['2.4 Project Kickoff - SCDF', '2.4.5.6', 'Civil Engineer', 'Receives BP.', '2.4.5.7'],
      ['2.4 Project Kickoff - SCDF', '2.4.5.7', 'Civil Engineer', 'Endorses BP.', '2.4.5.8'],
      ['2.4 Project Kickoff - SCDF', '2.4.5.8', 'Civil Engineer', 'Sends to PM.', '2.4.5.9'],
      ['2.4 Project Kickoff - SCDF', '2.4.5.9', 'Admin', 'Receives endorsed BP.', '2.4.5.10'],
      ['2.4 Project Kickoff - SCDF', '2.4.5.10', 'Admin', 'Encrypt BP.', '2.4.5.11'],
      ['2.4 Project Kickoff - SCDF', '2.4.5.11', 'Project Manager', 'Consolidate Documents from QPs.', '2.4.6'],

      ['2.4 Project Kickoff - SCDF', '2.4.6', '[N/A]', 'STAGE 2.4.6: SUBMISSION ON CORENET', '2.4.6.1'],
      ['2.4 Project Kickoff - SCDF', '2.4.6.1', 'Admin', 'Log onto Corenet (https://www.corenet.gov.sg/corenet/eSS/SoftwareDownloads/index.htm).', '2.4.6.2'],
      ['2.4 Project Kickoff - SCDF', '2.4.6.2', 'Admin', 'Request OTP from CE and ME.', '2.4.6.3'],
      ['2.4 Project Kickoff - SCDF', '2.4.6.3', 'Mechanical Engineer / Civil Engineer', 'Send OTP.', '2.4.6.4'],
      ['2.4 Project Kickoff - SCDF', '2.4.6.4', 'Admin', 'Receive OTP.', '2.4.6.5'],
      ['2.4 Project Kickoff - SCDF', '2.4.6.5', 'Project Manager', 'Prepare Draft Submission.', '2.4.6.6'],
      ['2.4 Project Kickoff - SCDF', '2.4.6.6', 'Project Manager', 'Verify details of Draft Submission.', '2.4.6.7'],
      ['2.4 Project Kickoff - SCDF', '2.4.6.7', 'Project Manager', 'Screenshot Submission & attachments.', '2.4.6.8'],
      ['2.4 Project Kickoff - SCDF', '2.4.6.8', 'Project Manager', 'Submit on Corenet.', '2.4.6.9'],
      ['2.4 Project Kickoff - SCDF', '2.4.6.9', 'Project Manager', 'Print acknowledgment of submission.', '2.4.6.10'],
      ['2.4 Project Kickoff - SCDF', '2.4.6.10', 'Project Manager', 'File screenshot of Summary & attachments.', '3.4']
    ];

    const formattedNew2_4 = new2_4.map(row => ({
        'File Name': row[0],
        'Step #': row[1],
        'Person-in-charge': row[2],
        'Step': row[3],
        'Next Step / Reference': row[4]
    }));

    let insertIndex = recordsWithout2_4.findIndex(r => r['File Name'].includes('3.1 Post-Submission'));
    if (insertIndex === -1) insertIndex = recordsWithout2_4.length; 

    let finalRecords = [
        ...recordsWithout2_4.slice(0, insertIndex),
        ...formattedNew2_4,
        ...recordsWithout2_4.slice(insertIndex)
    ];

    currentFileName = '';
    for (const r of finalRecords) {
        if (r['File Name'] === currentFileName) {
            r['File Name'] = '';
        } else {
            currentFileName = r['File Name'];
        }
    }

    const csvWriter = createCsvWriter({
        path: 'flow_cleaned_4col.csv',
        header: [
            {id: 'File Name', title: 'File Name'},
            {id: 'Step #', title: 'Step #'},
            {id: 'Person-in-charge', title: 'Person-in-charge'},
            {id: 'Step', title: 'Step'},
            {id: 'Next Step / Reference', title: 'Next Step / Reference'}
        ]
    });

    csvWriter.writeRecords(finalRecords)
        .then(() => {
            console.log('Done writing updated CSV with 2.4');
        });
  });
